### PR TITLE
Removed Swap files

### PR DESCRIPTION
**Pull request by Mnw2212**

### CODE REVIEW

**Comment by baishali-ghosh** [comment]
Thanks. Add this to VITOCW?

**Comment by Mnw2212** [comment]
Yep. Added it. Basically forked your repo to VITOCW.
Here's the link. https://github.com/VIT-OCW/CSE101
Woud be glad if you could push commits to the forked repo as well. :)

**Comment by aneesh-neelam** [comment]
@baishali-ghosh: Push commits to the forked repo only please. Makes it easier to track and keep things in one place. 

@Mnw2212: Add @baishali-ghosh to the organization.

**Comment by baishali-ghosh** [comment]
I'll push commits to the forked repo hereafter.

**Pull request merged**
